// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvb0_TeewMc4NpP-p8iyK8jGlK_ONFuJM',
    appId: '1:270396933897:web:28ce3b7990c649ddde35d8',
    messagingSenderId: '270396933897',
    projectId: 'medgo-a3ebf',
    authDomain: 'medgo-a3ebf.firebaseapp.com',
    databaseURL: 'https://medgo-a3ebf-default-rtdb.firebaseio.com',
    storageBucket: 'medgo-a3ebf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAw68VR31Orgr8F4rXxYQEsdJuWNJlHYc',
    appId: '1:270396933897:android:f212373993095a36de35d8',
    messagingSenderId: '270396933897',
    projectId: 'medgo-a3ebf',
    databaseURL: 'https://medgo-a3ebf-default-rtdb.firebaseio.com',
    storageBucket: 'medgo-a3ebf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApx_Wagb0LRganJQhWG9CTRnvmbcld2rA',
    appId: '1:270396933897:ios:2300d0419e1cc5fdde35d8',
    messagingSenderId: '270396933897',
    projectId: 'medgo-a3ebf',
    databaseURL: 'https://medgo-a3ebf-default-rtdb.firebaseio.com',
    storageBucket: 'medgo-a3ebf.appspot.com',
    iosClientId: '270396933897-9t2g90ogbe3us8ldb5a0j7kcqvic0eel.apps.googleusercontent.com',
    iosBundleId: 'com.example.medgo',
  );
}
